### ISSUE TITLE
Shouldnt the healtcheck fail URL be triggered?

### ISSUE THREAD

**Issue by l4t3b0** [pfidr34/docker-rclone#16] opened 2020-05-26 13:33 UTC
Hi pfidr34

I have a situation where the webdav server responded a 503 error code, but i did not get any failed notification from healtchecks.

I have 2 questions:
- based on my log, should not the fail URL be triggered?
- can i rely on the synchronization if i have such error in the log?

The log
```
2020/05/26 15:22:31 ERROR : Tamás/pics/2013/2013.12.28. Rap koncert: error listing: couldn't list files: 503 SERVICE UNAVAILABLE: 503 Service Unavailable
2020/05/26 15:22:31 Failed to ls with 2 errors: last error was: couldn't list files: 503 SERVICE UNAVAILABLE: 503 Service Unavailable
INFO: Source directory is not empty and can be processed without clear loss of data
INFO: Log file output to /logs/2020_05_26-15_22_31.txt
INFO: Sending start signal to healthchecks.io
--2020-05-26 15:22:31-- https://hc-ping.com/d34f5437-.......-9545b3f023cd/start
Resolving hc-ping.com... 178.63.26.145, 176.9.71.146, 159.69.66.229, ...
Connecting to hc-ping.com|178.63.26.145|:443... connected.
HTTP request sent, awaiting response... 200 OK
INFO: Starting rclone sync webdav-alapitvany-private:/Megosztott dokumentumok/ /data --config /config/rclone.conf -v --exclude /Forms/** --log-file=/logs/2020_05_26-15_22_31.txt
Length: 2 [text/plain]
Saving to: '/dev/null'

0K 100% 298K=0s

```

**Comment by pfidr34** [comment] 2020-05-26 13:39
In this case its failing on [line 61 of sync.sh](https://github.com/pfidr34/docker-rclone/blob/master/sync.sh#L61) when it tries to determine if the source directory is empty or not.

At the time it was written health checks were added after this check to determine if the actual rclone copy/move/sync command executed or not.

**Comment by pfidr34** [comment] 2020-05-26 13:45
**based on my log, should not the fail URL be triggered?**
In this case, no.

**can i rely on the synchronization if i have such error in the log?**
Depends. Is the job mission critical? If so, no.

I only backup between local/Google Drive/AWS/One Drive so i have not come across 503 errors. 

I'm sure something could be written to catch this but I'm not sure how I would replicate a 503 for testing. I would need to see what the return code of rclone ls/lsf is this case. If its a non 0 exit code I could trap it.

**Comment by l4t3b0** [comment] 2020-05-26 13:59
For testing purposes:

what if i write you a 5 line java program to statically respondes with http 503 for you?

would that help?

**Comment by pfidr34** [comment] 2020-05-26 14:05
If you can edit sync.sh you can just add some code prior to line 61 this should show us what the return code is in this case.

I can branch this and build it if needed.

```
rclone $RCLONE_DIR_CMD "$(eval echo $SYNC_SRC)" $RCLONE_OPTS
export RETURN_CODE=$?
echo "RETURN CODE: $RETURN_CODE"
if test "$(rclone $RCLONE_DIR_CMD "$(eval echo $SYNC_SRC)" $RCLONE_OPTS)"; then
    echo "INFO: Source directory is not empty and can be processed without clear loss of data"
```

**Comment by l4t3b0** [comment] 2020-05-27 10:19
Hi

I had difficulties reproducing the problem, but now i had a strange run that i performed manually from the container:

Here is the modified snippet that i have locally:
```
      rclone $RCLONE_CMD "$(eval echo $SYNC_SRC)" "$(eval echo $SYNC_DEST)" $RCLONE_OPTS $SYNC_OPTS_ALL
      export RETURN_CODE=$?
      set -e
    fi
  else
rclone $RCLONE_DIR_CMD "$(eval echo $SYNC_SRC)" $RCLONE_OPTS
export RETURN_CODE=$?
echo "RETURN CODE: $RETURN_CODE"
    if test "$(rclone $RCLONE_DIR_CMD "$(eval echo $SYNC_SRC)" $RCLONE_OPTS)"; then
    echo "INFO: Source directory is not empty and can be processed without clear loss of data"
    if [ ! -z "$OUTPUT_LOG" ]
```
And heres is my shell output:

> / # ./sync.sh
> INFO: Starting sync.sh pid 369 Wed May 27 12:13:41 CEST 2020
> INFO: Removing logs older than 120 day(s)...
> 2020/05/27 12:13:47 ERROR : : error listing: couldn't list files: 503 SERVICE UNAVAILABLE: 503 Service Unavailable
> 2020/05/27 12:13:47 Failed to ls with 2 errors: last error was: couldn't list files: 503 SERVICE UNAVAILABLE: 503 Service Unavailable
> / #
> 

It is strange that i dont have the RETURN CODE output.

I will have some other runs to see how it behaves and feed you some more logs

**Comment by l4t3b0** [comment] 2020-05-27 10:45
i had at least 2 other execution where i dont have the RETURN CODE output

**Comment by l4t3b0** [comment] 2020-05-27 12:46
Now i had a run, when the RESULT CODE is 0, but after that running the ls again received an 503.
The execution of the script stopped and i received the prompt back.

Looks like in case of 503 the script believes, that the source directory is empty :( ... but in my first comment's log it is not the case.

```
  1778245 Tamás/pics/2017/2017.10.20. Esküvő/Esküvői fotók/3_Kis_méretű_fotók_logós_(megtekintésre_színes)/Tamara&Tamás-99.jpg
RETURN CODE: 0
2020/05/27 14:42:34 ERROR : : error listing: couldn't list files: 503 SERVICE UNAVAILABLE: 503 Service Unavailable
2020/05/27 14:42:34 Failed to ls with 2 errors: last error was: couldn't list files: 503 SERVICE UNAVAILABLE: 503 Service Unavailable
WARNING: Source directory is empty. Skipping sync command.
/ #
```

**Comment by pfidr34** [comment] 2020-05-28 01:05
Not sure what we want to do here.
What do you think the expected behavior should be?

**Comment by l4t3b0** [comment] 2020-05-28 09:29
I found an ms document that tells me that the reason i receive 503 is because of throttling.

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online
"Server Too Busy"

But that is a different issue.

**Comment by l4t3b0** [comment] 2020-05-28 09:35
With your newest build i have the following situation now.
healthcheck tells me that the process started and not finished yet.

```
/logs # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 {entrypoint.sh} /bin/sh /entrypoint.sh
   65 root      0:00 /bin/sh
   85 root      0:00 crond -b -l 0 -L /tmp/crond.log
   86 root      0:00 tail -F /tmp/crond.log /tmp/sync.log
  121 root      0:00 /bin/sh
  141 root      0:00 ps -ef
/logs # ls -la
total 8
drwxr-xr-x    1 root     root            46 May 28 11:26 .
drwxr-xr-x    1 root     root           228 May 28 10:32 ..
-rw-r-----    1 root     root          5226 May 28 10:58 2020_05_28-10_50_27.txt
/logs # tail 2020_05_28-10_50_27.txt
2020/05/28 10:58:09 ERROR : Local file system at /data: not deleting directories as there were IO errors
2020/05/28 10:58:09 INFO  : There was nothing to transfer
2020/05/28 10:58:09 ERROR : Attempt 3/3 failed with 1 errors and: couldn't list files: 503 SERVICE UNAVAILABLE: 503 Service Unavailable
2020/05/28 10:58:09 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Checks:             34927 / 34927, 100%
Elapsed time:         0.0s

2020/05/28 10:58:09 Failed to sync: couldn't list files: 503 SERVICE UNAVAILABLE: 503 Service Unavailable
/logs #
```

So the sync.sh stopped working without triggering the fail URL.

I think this should be improved on your side and ignore the 503 - that i have to figure out myself how to fix.

**Comment by pfidr34** [comment] 2020-05-29 01:13
I have pushed a build to DockerHub for you to try. The tag is `pfidr/rclone:test`

I have to say, the way the rclone directory check works is a little different than the main rclone copy/move/sync call. 

So, depending on how this works I may need to scale back on how much effort I am going to put into this issue since the root of it is really just a throttling issue with Microsoft.

That being said, if you want to continue to troubleshoot on your own and submit a pull request for review I would be happy to review and merge if it looks good.

**Comment by l4t3b0** [comment] 2020-05-29 07:48
I think we have a misunderstanding.
From my point of view there are two **independent** problems here:
- 503, that is a throttling issue - you have nothing to do with that, i have to fix it.
- some error handling issue that causes the script to finish abnormally

It is a fortunate  that i have the 503 problem and i can reproduce it, because i have the chance to help you to fix the error handling problem.

Thanks for your new image. i will give it a try.

**Comment by pfidr34** [comment] 2020-05-29 13:19
"some error handling issue that causes the script to finish abnormally"

This is what I tried to address in my test build. 

at the top of sync.sh I have a `set -e`. This causes the script (and container) to exit if an error is encountered. 

What I did was wrap the directory check in a `set +e` and `set -e` to "allow" errors in that portion of the script without exiting.

Let me know if it works.

**Comment by pfidr34** [comment] 2020-06-09 02:18
@l4t3b0 I have pushed that change to production, I am going to close this issue.

**Closed as completed by pfidr34** 2020-06-09 02:18 UTC
